/**
 *  Copyright (C) 2010 eXo Platform SAS.
 *
 *  This is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as
 *  published by the Free Software Foundation; either version 2.1 of
 *  the License, or (at your option) any later version.
 *
 *  This software is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this software; if not, write to the Free
 *  Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 *  02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, 
// vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.31 at 12:14:05 PM EEST 
//

package org.xcmis.client.gwt.client.model;

/**
 * @author 
 * @version $Id: 
 *
 */
public enum EnumVersioningState 
{

   /**
    * Checked out.
    */
   CHECKEDOUT("checkedout"), 
   
   /**
    * Minor.
    */
   MINOR("minor"), 
   
   /**
    * Major.
    */
   MAJOR("major"), 
   
   /**
    * None.
    */
   NONE("none");
   
   /**
    * Value.
    */
   private final String value;

   /**
    * @param v value
    */
   EnumVersioningState(String v)
   {
      value = v;
   }

   /**
    * @return String
    */
   public String value()
   {
      return value;
   }

   /**
    * @param v value
    * @return {@link EnumVersioningState}
    */
   public static EnumVersioningState fromValue(String v)
   {
      for (EnumVersioningState c : EnumVersioningState.values())
      {
         if (c.value.equals(v))
         {
            return c;
         }
      }
      throw new IllegalArgumentException(v);
   }

}
